"""MIDI directory export — master.mid + tracks/ + manifest.json + README.txt."""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from chemsymphony.core import MidiResult


def save_midi_directory(result: "MidiResult", directory: Path) -> None:
    """Save a MidiResult to a directory structure."""
    directory.mkdir(parents=True, exist_ok=True)
    tracks_dir = directory / "tracks"
    tracks_dir.mkdir(exist_ok=True)

    # Write master MIDI
    (directory / "master.mid").write_bytes(result.master)

    # Write individual tracks
    for i, (name, data) in enumerate(result.tracks, start=1):
        filename = f"{i:02d}_{name}.mid"
        (tracks_dir / filename).write_bytes(data)

    # Write manifest
    manifest_path = directory / "manifest.json"
    manifest_path.write_text(json.dumps(result.manifest, indent=2))

    # Write README
    smiles = result.manifest.get("smiles_canonical", "unknown")
    formula = result.manifest.get("molecular_formula", "unknown")
    readme_lines = [
        f"ChemSymphony MIDI Export",
        f"========================",
        f"",
        f"Molecule: {formula}",
        f"SMILES:   {smiles}",
        f"",
        f"Files:",
        f"  master.mid          - Combined MIDI (all tracks)",
        f"  manifest.json       - Full mapping metadata",
        f"  tracks/             - Individual MIDI tracks",
    ]
    for i, (name, _) in enumerate(result.tracks, start=1):
        readme_lines.append(f"    {i:02d}_{name}.mid")
    readme_lines.append("")
    readme_lines.append("Generated by ChemSymphony")

    (directory / "README.txt").write_text("\n".join(readme_lines))
